### ISSUE TITLE
Question about the thomas/dirty_bloom_tp branch in HuggingFace/Transformers

### ISSUE THREAD

**Issue by HenryChang213** [huggingface/transformers_bloom_parallel#9]
I ran across your amazing [blog](https://huggingface.co/blog/bloom-inference-optimization) about how you optimize the inference of Bloom model. I notice that the thomas/dirty_bloom_tp branch is different from the main branch. Could you please tell me which branch I should use to run the inference with your optimization techniques? I am a first-year PhD student at Princeton and am currently benchmarking LLMs from a throughput and latency perspective.

**Comment by HenryChang213** [comment]
The newest branch I find is thomas/add_custom_kernels.

**Comment by Narsil** [comment]
Currently you should take a look at https://github.com/huggingface/text-generation-inference
It's the latest code containing most of the optimizations and more features.

Use the docker directly is the easiest way to get reproducible benchmarks.

**Comment by Narsil** [comment]
I'll close this, feel free to reopen if that doesn't answer your question.
